### Register User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Victor",
    "email": "yeremiavictor@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "admin"
}

### Register User biasa
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Coba",
    "email": "coba@gmail.com",
    "password": "12345678",
    "confPassword": "12345678",
    "role": "user"
}

### Get All User
GET http://localhost:5000/users

### Get Data By ID
GET http://localhost:5000/users/90d13414-ceb9-4aac-8c2c-fcf4ec599952

### Update User
PATCH  http://localhost:5000/users/90d13414-ceb9-4aac-8c2c-fcf4ec599952
Content-Type: application/json

{
    "name": "Victor Updated",
    "email": "yeremiavictor@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

### delete User
DELETE http://localhost:5000/users/90d13414-ceb9-4aac-8c2c-fcf4ec599952