### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "yeremiavictor@gmail.com",
    "password": "12345678"
}

### Login untuk Jelata wkwkkw
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "coba@gmail.com",
    "password": "12345678"
}

### Me
Get http://localhost:5000/Me

### Logout
DELETE http://localhost:5000/Logout